name = "SnowflakePlots"
uuid = "fa4a7b36-de81-424e-b6b4-6a78b5e46525"
authors = ["Alireza Yazdi <alireza@anyonsys.com>", "Paul Le Roux <pleroux@anyonsys.com>", "Facundo Sosa-Rey <facundo@anyonsys.com>", "Nicolas Poirier <nicolas.poirier2@mail.mcgill.ca>"]
version = "0.1.0"

[deps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Snowflake = "7bd9edc1-4fdc-40a1-a0f6-da58fb4f45eb"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Plots = "1.25"
StatsBase = "0.32 - 0.33"
